### PR TITLE
Add basic Docker container tests

### LINKED ISSUE #4: Add basic container tests
There are no real tests for this project.  Add some low-hanging fruit like the ones in [guacamole-composition/tests](https://github.com/cisagov/guacamole-composition/tree/develop/tests).

### PR DESCRIPTION
**Pull request by dav3r**
# 

## 🗣 Description
This PR adds some tests to ensure that the Docker containers start up as expected.
While I was here, I also cleaned up an outdated thang in `setup.py`.

Resolves #4.

## 💭 Motivation and Context
No tests bad.
Some tests better than no tests.

## 🧪 Testing
`pytest` is successful and all of the pre-commit tests pass too. Huzzah!

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests ~to cover my changes~.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
I like this. It would be nice if `pytest` was added to the GitHub Actions workflow though (such as in [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library/blob/6505b32ea4732654e3a207dd91a50823db146084/.github/workflows/build.yml#L47)).

**Review by felddy — APPROVED** [review]
NIce Docker testing!  🐳

**Comment by dav3r** [comment]
> I like this. It would be nice if `pytest` was added to the GitHub Actions workflow though (such as in [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library/blob/6505b32ea4732654e3a207dd91a50823db146084/.github/workflows/build.yml#L47)).

Excellent suggestion @mcdonnnj - see https://github.com/cisagov/pca-gophish-composition/pull/6/commits/161eadf087ebe6f565f06963aad005c88b4f61d9 and https://github.com/cisagov/pca-gophish-composition/pull/6/commits/6ca00f52c8c067bf6d20e0117df1af78d3eee3c8 for that change.

**Review by jsf9k — APPROVED** [review]
Nice.  I'm liking the tests.

**Pull request merged**
