### PR TITLE
Update name of package from `gophish_init` to `gophish-init`

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request updates the name of the Python package from `gophish_init` to `gophish-init`.

## 💭 Motivation and context ##

We discovered in cisagov/ansible-role-pca-gophish-composition#52 that older versions of `pip` normalize the package name (converting underscores to hyphens) while at least one newer version does not.  To ensure that the package name is not modified by `pip` and has the expected value, we change it to its normalized form.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Comment by jsf9k** [comment]
Note that the name of the package has definitely changed, and the console script still runs:
```console
pca-gophish-composition on  improvement/rename-package via 🐍 v3.11.9 (pca-gophish-composition) 
❯ pip list | grep -i gophish-init
gophish-init      0.5.0rc1  /home/jeremy_frasier/cisagov/pca-gophish-composition/src
pca-gophish-composition on  improvement/rename-package via 🐍 v3.11.9 (pca-gophish-composition) 
❯ gophish-init --help
Gophish-init is a configuration utility for Gophish.

Usage:
  gophish-init [--log-level=LEVEL] [--url=URL] API_KEY
  gophish-init (-h | --help)

Options:
  -h --help              Show this message.
  --url=url              URL for Gophish API endpoint [default: https://localhost:3333]
  --log-level=LEVEL      If specified, then the log level will be set to
                         the specified value.  Valid values are "debug", "info",
                         "warning", "error", and "critical". [default: warning]
```

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by mcdonnnj — APPROVED** [review]
:shipit: @jsf9k Just to note: When I was testing this (from conversations in https://github.com/cisagov/ansible-role-pca-gophish-composition/pull/52) I tried every single point release of `pip` starting with the version on Fedora 39 and through to the latest when I was testing (`24.0`) and saw the same behavior exhibited.

**Comment by jsf9k** [comment]
> :shipit: @jsf9k Just to note: When I was testing this (from conversations in [cisagov/ansible-role-pca-gophish-composition#52](https://github.com/cisagov/ansible-role-pca-gophish-composition/pull/52)) I tried every single point release of `pip` starting with the version on Fedora 39 and through to the latest when I was testing (`24.0`) and saw the same behavior exhibited.

I guess we know it's the new default `pip` behavior then, and that confirms that this change was the right thing to do.

**Pull request merged**
